# Generated by Django 5.1.7 on 2025-04-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passwordresetotp',
            table='authentication_passwordresetotp',
        ),
    ]
