# Generated by Django 5.2 on 2025-04-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'get_latest_by': 'created_at'},
        ),
    ]
