from django.db import models


class StateChoices(models.IntegerChoices):
    ALABAMA = 1, "Alabama"
    ALASKA = 2, "Alaska"
    ARIZONA = 3, "Arizona"
    ARKANSAS = 4, "Arkansas"
    CALIFORNIA = 5, "California"
    COLORADO = 6, "Colorado"
    CONNECTICUT = 7, "Connecticut"
    DELAWARE = 8, "Delaware"
    FLORIDA = 9, "Florida"
    GEORGIA = 10, "Georgia"
    HAWAII = 11, "Hawaii"
    IDAHO = 12, "Idaho"
    ILLINOIS = 13, "Illinois"
    INDIANA = 14, "Indiana"
    IOWA = 15, "Iowa"
    KANSAS = 16, "Kansas"
    KENTUCKY = 17, "Kentucky"
    LOUISIANA = 18, "Louisiana"
    MAINE = 19, "Maine"
    MARYLAND = 20, "Maryland"
    MASSACHUSETTS = 21, "Massachusetts"
    MICHIGAN = 22, "Michigan"
    MINNESOTA = 23, "Minnesota"
    MISSISSIPPI = 24, "Mississippi"
    MISSOURI = 25, "Missouri"
    MONTANA = 26, "Montana"
    NEBRASKA = 27, "Nebraska"
    NEVADA = 28, "Nevada"
    NEW_HAMPSHIRE = 29, "New Hampshire"
    NEW_JERSEY = 30, "New Jersey"
    NEW_MEXICO = 31, "New Mexico"
    NEW_YORK = 32, "New York"
    NORTH_CAROLINA = 33, "North Carolina"
    NORTH_DAKOTA = 34, "North Dakota"
    OHIO = 35, "Ohio"
    OKLAHOMA = 36, "Oklahoma"
    OREGON = 37, "Oregon"
    PENNSYLVANIA = 38, "Pennsylvania"
    RHODE_ISLAND = 39, "Rhode Island"
    SOUTH_CAROLINA = 40, "South Carolina"
    SOUTH_DAKOTA = 41, "South Dakota"
    TENNESSEE = 42, "Tennessee"
    TEXAS = 43, "Texas"
    UTAH = 44, "Utah"
    VERMONT = 45, "Vermont"
    VIRGINIA = 46, "Virginia"
    WASHINGTON = 47, "Washington"
    WEST_VIRGINIA = 48, "West Virginia"
    WISCONSIN = 49, "Wisconsin"
    WYOMING = 50, "Wyoming"


class Services(models.IntegerChoices):
    SURVEILLANCE = 0, "Surveillance"
    DIAGNOSIS = 1, "Diagnosis"
    SCREENING = 2, "Screening"
    SECOND_OPINION = 3, "Second Opinion"
    GENERAL = 4, "General"
    FOLLOW_UP = 5, "Follow Up"


class Months(models.IntegerChoices):
    JANUARY = 1, "January"
    FEBRUARY = 2, "February"
    MARCH = 3, "March"
    APRIL = 4, "April"
    MAY = 5, "May"
    JUNE = 6, "June"
    JULY = 7, "July"
    AUGUST = 8, "August"
    SEPTEMBER = 9, "September"
    OCTOBER = 10, "October"
    NOVEMBER = 11, "November"
    DECEMBER = 12, "December"


# ensure the number are same as in python this is the correct mapping
class DaysOfWeek(models.IntegerChoices):
    MONDAY = 0, "Monday"
    TUESDAY = 1, "Tuesday"
    WEDNESDAY = 2, "Wednesday"
    THURSDAY = 3, "Thursday"
    FRIDAY = 4, "Friday"
    SATURDAY = 5, "Saturday"
    SUNDAY = 6, "Sunday"
