# Generated by Django 5.1.7 on 2025-05-09 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='doctors.timeslot'),
        ),
        migrations.AddIndex(
            model_name='appointments',
            index=models.Index(fields=['patient'], name='appointment_patient_75a4eb_idx'),
        ),
    ]
