# Generated by Django 5.1.7 on 2025-05-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0004_alter_service_name'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_patient_229523_idx',
            old_name='appointment_patient_75a4eb_idx',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
