# Generated by Django 5.1.7 on 2025-05-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointments', to='doctors.timeslot'),
        ),
    ]
