# Generated by Django 5.1.7 on 2025-04-23 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='id',
        ),
        migrations.AddField(
            model_name='appointments',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
