# Generated by Django 5.1.7 on 2025-06-11 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_time_slot'),
        ('doctors', '0004_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='doctors.timeslot'),
        ),
    ]
