# Generated by Django 5.1.7 on 2025-05-03 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointments_status'),
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.timeslot'),
        ),
    ]
