# Generated by Django 5.1.7 on 2025-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reschedule_fee_paid',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled')], db_default=0),
        ),
    ]
