# Generated by Django 5.1.7 on 2025-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_appointment_reschedule_fee_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
