# Generated by Django 5.1.7 on 2025-06-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status'),
        ('appointments', '0009_appointment_patient_snapshot'),
    ]

    operations = [
    ]
