# Generated by Django 5.1.7 on 2025-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_merge_20250618_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled'), (6, 'Canceled_Refunded')], db_default=0),
        ),
    ]
