# Generated by Django 5.1.7 on 2025-06-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_snapshot',
        ),
    ]
