# Generated by Django 5.1.7 on 2025-06-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_remove_appointment_patient_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.IntegerField(choices=[(0, 'Surveillance'), (1, 'Diagnosis'), (2, 'Screening'), (3, 'Second Opinion')], default=1),
            preserve_default=False,
        ),
    ]
