# Generated by Django 5.2 on 2025-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Doctor'), (2, 'Patient')], default=2, verbose_name='role'),
        ),
    ]
