# Generated by Django 5.1.7 on 2025-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Doctor'), (2, 'Patient')], default=2, verbose_name='role'),
        ),
    ]
