# Generated by Django 5.1.7 on 2025-05-12 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorservice',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_services', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='licenseinfo',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_info', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='doctorservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='doctor_services', to='doctors.service'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='doctors', to='doctors.specialization'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='doctors.doctor'),
        ),
        migrations.AddIndex(
            model_name='licenseinfo',
            index=models.Index(fields=['doctor'], name='license_inf_doctor__836167_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorservice',
            unique_together={('doctor', 'service')},
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialization'], name='doctor_special_e825bb_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['doctor'], name='time_slot_doctor__c67b77_idx'),
        ),
    ]
