# Generated by Django 5.1.7 on 2025-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.IntegerField(choices=[(1, 'Surveillance'), (2, 'Diagnosis'), (3, 'Screening'), (4, 'Second Opinion')]),
        ),
    ]
