# Generated by Django 5.1.7 on 2025-04-23 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_services_alter_doctor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
