# Generated by Django 5.1.7 on 2025-05-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.IntegerField(choices=[(0, 'Surveillance'), (1, 'Diagnosis'), (2, 'Screening'), (3, 'Second Opinion')]),
        ),
    ]
