# Generated by Django 5.1.7 on 2025-04-30 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iodineallergy',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iodine_allergy', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='cancerhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_history', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='addictionhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addiction_history', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.pharmacist'),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_physician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.primaryphysician'),
        ),
        migrations.AddField(
            model_name='patient',
            name='surgical_history',
            field=models.ManyToManyField(blank=True, related_name='patients', to='patients.surgicalhistory'),
        ),
    ]
