# Generated by Django 5.1.7 on 2025-05-09 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iodineallergy',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iodine_allergy', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='cancerhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_history', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='addictionhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addiction_history', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='allergy_patients', to='patients.allergy'),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientcareprovider',
            name='care_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='care_provider_patients', to='patients.careprovider'),
        ),
        migrations.AddField(
            model_name='patientcareprovider',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_providers', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='medical_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medical_history_patients', to='patients.medicalhistory'),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medication_patients', to='patients.medication'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientsurgicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_histories', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientsurgicalhistory',
            name='surgical_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='surgical_history_patients', to='patients.surgicalhistory'),
        ),
        migrations.AddField(
            model_name='treatmentrecieved',
            name='cancer_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_received', to='patients.cancerhistory'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['visit_type'], name='patient_visit_t_c2bb79_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['state'], name='patient_state_fe014a_idx'),
        ),
    ]
