# Generated by Django 5.2 on 2025-04-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_iodine_contrast_allergic',
            field=models.BooleanField(default=False),
        ),
    ]
