# Generated by Django 5.1.7 on 2025-06-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicalrecord',
            name='appointment_uuid',
        ),
    ]
