# Generated by Django 5.1.7 on 2025-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerhistory',
            name='treatment_recieved',
            field=models.IntegerField(blank=True, choices=[(0, 'Chemotherapy'), (1, 'Radiation Therapy'), (2, 'Surgery'), (3, 'Other')], default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TreatmentRecieved',
        ),
    ]
