# Generated by Django 5.1.7 on 2025-05-20 15:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='medical_condition',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='surgicalhistory',
            old_name='surgical_condition',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='careprovider',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
