# Generated by Django 5.1.7 on 2025-05-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_cancerhistory_treatment_recieved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancerhistory',
            old_name='treatment_recieved',
            new_name='treatment_received',
        ),
    ]
