# Generated by Django 5.1.7 on 2025-05-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('patients', '0003_rename_medical_condition_medicalhistory_name_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patient',
            new_name='patient_state_i_157aa2_idx',
            old_name='patient_state_fe014a_idx',
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region'),
        ),
    ]
