# Generated by Django 5.2 on 2025-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_iodineallergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Non-binary'), (3, 'Prefer not to say')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Married'), (1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'Separated'), (5, 'Other')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Cancer Screening'), (1, 'Cancer Treatment Second Opinion'), (2, 'Cancer Surveillance'), (3, 'Oncology Nurse Support'), (4, 'Follow-Up Visit'), (5, 'Initial Consultation')]),
        ),
    ]
