# Generated by Django 5.1.7 on 2025-06-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_visit_t_c2bb79_idx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='visit_type',
        ),
    ]
