# Generated by Django 5.1.7 on 2025-05-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_treatment_recieved_cancerhistory_treatment_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Non-binary'), (3, 'Prefer not to say')], null=True),
        ),
    ]
