# Generated by Django 5.1.7 on 2025-05-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Married'), (1, 'Single'), (2, 'Divorced'), (3, 'Widowed'), (4, 'Separated'), (5, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='visit_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Cancer Screening'), (1, 'Cancer Treatment Second Opinion'), (2, 'Cancer Surveillance'), (3, 'Oncology Nurse Support'), (4, 'Follow-Up Visit'), (5, 'Initial Consultation')], null=True),
        ),
    ]
