# Generated by Django 5.1.7 on 2025-05-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iodineallergy',
            name='is_iodine_allergic',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Unknown')]),
        ),
    ]
