# Generated by Django 5.1.7 on 2025-04-20 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='services',
            field=models.CharField(blank=True, choices=[('SERVEILLANCE', 'Serveillance'), ('DIAGNOSIS', 'Diagnosis'), ('SCREENING', 'Screening'), ('SECOND_OPINION', 'Second Opinion')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
