# Generated by Django 5.1.7 on 2025-06-27 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('refund_type', models.IntegerField(choices=[(1, 'Full Refund'), (2, 'Partial Refund'), (3, 'No Refund')])),
                ('hours_before_min', models.PositiveIntegerField(help_text='Minimum hours before the appointment to apply this refund policy')),
                ('hours_before_max', models.PositiveIntegerField(help_text='Maximum hours before the appointment to apply this refund policy')),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_client_secret', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.IntegerField(choices=[(1, 'Requires Payment Method'), (2, 'Requires Confirmation'), (3, 'Requires Action'), (4, 'Processing'), (5, 'Succeeded'), (6, 'Canceled'), (7, 'Refunded'), (8, 'Failed')], default=1)),
                ('appointment_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID of the related appointment', null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=255)),
                ('receipt_email', models.EmailField(blank=True, max_length=254)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='appointments.appointment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reservations', to='doctors.timeslot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentPaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Requires Action'), (2, 'Succeeded'), (3, 'Failed'), (4, 'Cancelled')], default=1)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_payment', models.ForeignKey(help_text='The payment that is being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.appointmentpayment')),
                ('refund_policy', models.ForeignKey(blank=True, help_text='Refund policy applied to this refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.refundpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
