# Generated by Django 5.1.7 on 2025-05-31 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_client_secret', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.IntegerField(choices=[(1, 'Requires Payment Method'), (2, 'Requires Confirmation'), (3, 'Requires Action'), (4, 'Processing'), (5, 'Succeeded'), (6, 'Canceled'), (7, 'Failed')], default=1)),
                ('payment_method_id', models.CharField(blank=True, max_length=255)),
                ('receipt_email', models.EmailField(blank=True, max_length=254)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='appointments.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
