# Generated by Django 5.1.7 on 2025-06-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentpayment',
            name='appointment_uuid',
        ),
        migrations.RemoveField(
            model_name='appointmentpayment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointmentpayment',
            name='receipt_email',
        ),
        migrations.RemoveField(
            model_name='appointmentpayment',
            name='time_slot',
        ),
    ]
