# Generated by Django 5.1.7 on 2025-06-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_time_slot'),
        ('doctors', '0004_alter_service_name'),
        ('patients', '0004_alter_patient_gender'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentpayment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='appointmentpayment',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='Reserved timeslot for this payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reservations', to='doctors.timeslot'),
        ),
        migrations.AlterField(
            model_name='appointmentpayment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='appointments.appointment'),
        ),
    ]
