# Generated by Django 5.1.7 on 2025-06-14 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_service_name'),
        ('payments', '0002_appointmentpayment_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('refund_type', models.IntegerField(choices=[(1, 'Full Refund'), (2, 'Partial Refund'), (3, 'No Refund')], max_length=20)),
                ('hours_before_min', models.PositiveIntegerField(help_text='Minimum hours before the appointment to apply this refund policy')),
                ('hours_before_max', models.PositiveIntegerField(help_text='Maximum hours before the appointment to apply this refund policy')),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='appointmentpayment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Requires Payment Method'), (2, 'Requires Confirmation'), (3, 'Requires Action'), (4, 'Processing'), (5, 'Succeeded'), (6, 'Canceled'), (7, 'Refunded'), (8, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='appointmentpayment',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reservations', to='doctors.timeslot'),
        ),
        migrations.CreateModel(
            name='AppointmentPaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Requires Action'), (2, 'Succeeded'), (3, 'Failed'), (4, 'Cancelled')], default=1)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_payment', models.ForeignKey(help_text='The payment that is being refunded', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.appointmentpayment')),
                ('refund_policy', models.ForeignKey(blank=True, help_text='Refund policy applied to this refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='payments.refundpolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
