# Generated by Django 5.1.7 on 2025-06-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_refundpolicy_alter_appointmentpayment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentpayment',
            name='appointment_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the related appointment', null=True),
        ),
        migrations.AlterField(
            model_name='refundpolicy',
            name='refund_type',
            field=models.IntegerField(choices=[(1, 'Full Refund'), (2, 'Partial Refund'), (3, 'No Refund')]),
        ),
    ]
