# Generated by Django 5.1.7 on 2025-07-07 18:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100, unique=True)),
                ('log_reads', models.BooleanField(default=True)),
                ('log_creates', models.BooleanField(default=True)),
                ('log_updates', models.BooleanField(default=True)),
                ('log_deletes', models.BooleanField(default=True)),
                ('deduplicate_reads_within_minutes', models.PositiveIntegerField(default=5)),
                ('track_page_time', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_log_configuration',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.IntegerField(choices=[(0, 'Admin'), (1, 'Doctor'), (2, 'Nurse'), (3, 'Patient')], default=0)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.IntegerField(choices=[(0, 'Create'), (1, 'Read'), (2, 'Update'), (3, 'Delete')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Success'), (1, 'Failure'), (2, 'Pending')], default=0)),
                ('action_type', models.CharField(choices=[(0, 'Create'), (1, 'Read'), (2, 'Update'), (3, 'Delete')], max_length=10, verbose_name='Action')),
                ('object_id', models.CharField(blank=True, null=True)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_accessed', models.CharField(max_length=255)),
                ('resource_id', models.CharField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('page_entry_time', models.DateTimeField(blank=True, null=True)),
                ('page_exit_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DurationField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('page_url', models.URLField(max_length=500)),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='audits.auditlog')),
            ],
            options={
                'db_table': 'audit_log_access',
                'ordering': ['-access_time'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(0, 'Admin'), (1, 'Doctor'), (2, 'Nurse'), (3, 'Patient')])),
                ('resource_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total_actions', models.PositiveIntegerField(default=0)),
                ('create_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('delete_count', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0)),
                ('first_access', models.DateTimeField()),
                ('last_access', models.DateTimeField()),
                ('access_times', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log_summary',
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='audit_logs_action__11f9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'timestamp'], name='audit_logs_resourc_4f6f11_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_logs_ip_addr_932507_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogsummary',
            index=models.Index(fields=['date', 'user_type'], name='audit_log_s_date_89768e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogsummary',
            index=models.Index(fields=['user', 'date'], name='audit_log_s_user_id_6ad38a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditlogsummary',
            unique_together={('user', 'resource_type', 'date')},
        ),
    ]
